"""extend models for university side

Revision ID: d146aa1f283f
Revises: 
Create Date: 2026-02-20 12:05:40.554700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd146aa1f283f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_comment', schema=None) as batch_op:
        batch_op.drop_constraint('community_comment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'community_post', ['post_id'], ['id'])

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('university_id', sa.Integer(), nullable=True))
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='数据异常/功能建议/其他',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='0:待处理, 1:已回复',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.create_foreign_key(None, 'university', ['university_id'], ['id'])

    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.drop_constraint('knowledge_base_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'university', ['university_id'], ['id'])

    with op.batch_alter_table('major', schema=None) as batch_op:
        batch_op.drop_index('idx_major_name')
        batch_op.create_index(batch_op.f('ix_major_name'), ['name'], unique=False)
        batch_op.drop_constraint('major_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'university', ['university_id'], ['id'])

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher_type', sa.String(length=20), nullable=True))
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='政策/技巧/公告',
               existing_nullable=True)

    with op.batch_alter_table('qa_prompt_template', schema=None) as batch_op:
        batch_op.alter_column('template_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='通用/高校',
               existing_nullable=False)

    with op.batch_alter_table('qa_records', schema=None) as batch_op:
        batch_op.alter_column('response_time',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='毫秒',
               existing_nullable=True)

    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_constraint('student_profile_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sys_user', ['user_id'], ['id'])

    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university_id', sa.Integer(), nullable=True))
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='student/admin/university',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='1:可用, 0:禁用, 2:待审核',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_index('username')
        batch_op.create_index(batch_op.f('ix_sys_user_username'), ['username'], unique=True)
        batch_op.create_foreign_key(None, 'university', ['university_id'], ['id'])

    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_file_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('audit_status', sa.Integer(), nullable=True))
        batch_op.alter_column('level',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='985/211/双高/普通',
               existing_nullable=True)
        batch_op.drop_index('idx_uni_name')
        batch_op.create_index(batch_op.f('ix_university_name'), ['name'], unique=False)

    with op.batch_alter_table('university_faq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_weight', sa.Integer(), nullable=True))
        batch_op.drop_constraint('university_faq_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'university', ['university_id'], ['id'])

    with op.batch_alter_table('volunteer_plan', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='备选库/模拟方案',
               existing_nullable=False)
        batch_op.drop_constraint('volunteer_plan_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sys_user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_plan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('volunteer_plan_ibfk_1', 'sys_user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='备选库/模拟方案',
               existing_nullable=False)

    with op.batch_alter_table('university_faq', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('university_faq_ibfk_1', 'university', ['university_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('sort_weight')

    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_university_name'))
        batch_op.create_index('idx_uni_name', ['name'], unique=False)
        batch_op.alter_column('level',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='985/211/双高/普通',
               existing_nullable=True)
        batch_op.drop_column('audit_status')
        batch_op.drop_column('auth_file_url')

    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sys_user_username'))
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='1:可用, 0:禁用, 2:待审核',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='student/admin/university',
               existing_nullable=False)
        batch_op.drop_column('university_id')

    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('student_profile_ibfk_1', 'sys_user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('qa_records', schema=None) as batch_op:
        batch_op.alter_column('response_time',
               existing_type=mysql.INTEGER(),
               comment='毫秒',
               existing_nullable=True)

    with op.batch_alter_table('qa_prompt_template', schema=None) as batch_op:
        batch_op.alter_column('template_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='通用/高校',
               existing_nullable=False)

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='政策/技巧/公告',
               existing_nullable=True)
        batch_op.drop_column('publisher_type')

    with op.batch_alter_table('major', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('major_ibfk_1', 'university', ['university_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_major_name'))
        batch_op.create_index('idx_major_name', ['name'], unique=False)

    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('knowledge_base_ibfk_1', 'university', ['university_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='0:待处理, 1:已回复',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='数据异常/功能建议/其他',
               existing_nullable=True)
        batch_op.drop_column('university_id')
        batch_op.drop_column('feedback_source')

    with op.batch_alter_table('community_comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('community_comment_ibfk_1', 'community_post', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
